
import React from 'react';
import { Modal } from './ui/Modal';

interface CopyrightPanelProps {
    isOpen: boolean;
    onClose: () => void;
}

export const CopyrightPanel: React.FC<CopyrightPanelProps> = ({ isOpen, onClose }) => {
    return (
        <Modal isOpen={isOpen} onClose={onClose} title="Copyright & Data Ownership" size="lg">
            <div className="space-y-6 text-sm text-gray-600 dark:text-gray-300 leading-relaxed pb-4 px-1">
                <section>
                    <h4 className="font-bold text-gray-900 dark:text-gray-100 mb-1.5 text-base">Your Content Remains Yours</h4>
                    <p>You retain full ownership of every document you upload and all data extracted from those documents. DataExtract AI does not claim any rights, title, or interest in your files or the resulting information.</p>
                </section>

                <section>
                    <h4 className="font-bold text-gray-900 dark:text-gray-100 mb-1.5 text-base">AI Processing & Privacy</h4>
                    <p>Our AI models access your documents strictly to perform the extraction you request. Your files are never used to train our models or improve our systems. Processing is transient and occurs only upon your command.</p>
                </section>

                <section>
                    <h4 className="font-bold text-gray-900 dark:text-gray-100 mb-1.5 text-base">Rights to Generated Outputs</h4>
                    <p>All exported files (JSON, CSV, PDF, Text) belong entirely to you. You have the unrestricted right to use, modify, distribute, and commercialize these outputs.</p>
                </section>

                <section>
                    <h4 className="font-bold text-gray-900 dark:text-gray-100 mb-1.5 text-base">Attribution Mark</h4>
                    <p>Exported files may include a small "Generated by DataExtract AI" watermark. This is solely for attribution and brand identity only; it does not affect your ownership of the data contained within the file.</p>
                </section>

                <section>
                    <h4 className="font-bold text-gray-900 dark:text-gray-100 mb-1.5 text-base">Platform Intellectual Property</h4>
                    <p>The DataExtract AI interface, underlying code, workflow designs, and branding are the proprietary property of the platform. While you own your data, the software tool itself is protected by copyright and may not be duplicated or resold.</p>
                </section>

                <div className="pt-6 border-t border-gray-100 dark:border-white/5">
                    <p className="font-medium text-[#007AFF]">Privacy and user control are core principles of DataExtract AI.</p>
                </div>
            </div>
        </Modal>
    );
};
